-- AlterTable
ALTER TABLE "Cohort" ADD COLUMN     "color" TEXT DEFAULT '#000000',
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
