import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "../_trpc/Provider";
import Navbar from "@/components/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gefest Builders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Navbar></Navbar>
      <div className="pt-8">{children}</div>
    </div>
  );
}
