import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "../_trpc/Provider";
import "swiper/css";
import Navbar from "@/components/navbar";
//@ts-ignore
import riveWASMResource from "node_modules/@rive-app/canvas/rive.wasm";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <head>
        <title>Gefest Builders</title>
      </head>
      <body>
        <Navbar></Navbar>
        <div className="pt-8">{children}</div>
      </body>
    </>
  );
}
