import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import "swiper/css";
import Navbar from "@/components/navbar";
import { Analytics } from "@vercel/analytics/react";

//@ts-ignore
import riveWASMResource from "node_modules/@rive-app/canvas/rive.wasm";
import Provider from "./_trpc/Provider";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Gefest Builders</title>
        <link
          rel="preload"
          href={riveWASMResource}
          as="fetch"
          crossOrigin="anonymous"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        {/* <meta
          property="og:image"
          content="https://popupsmart.com/blog/user/pages/365.free-keyword-research-tools/Free-keyword-research-tools-cover.png"
        />

        <meta property="og:title" content="Your Title" />

        <meta
          property="og:description"
          content="A full description of the page."
        />

        <meta property="og:image:width" content="1200" />

        <meta property="og:image:height" content="630" /> */}
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <UserProvider>
        <Provider>
          <body className={inter.className}>
            {children}
            <Toaster />
            <Analytics />
          </body>
        </Provider>
      </UserProvider>
    </html>
  );
}
